### ISSUE TITLE
works with more file types than just aiff?

### ISSUE THREAD

**Issue by dwmorrin** [jaredellison/audio_to_header#2]
I just tried it on a .wav file, and it appears to have worked fine.  The program did not complain, file was generated.  I did not verify the output is usable, but the numbers look ok.

Any reason why you're advertising this as aiff only?

**Comment by jaredellison** [comment]
Good point! The Soundfile supports a number of different formats so this is likely to support more than `.aiff` sources although for now it only handles one channel of audio. Closing this and renaming the repo with  #4.
